import { View, Text } from 'react-native'
import React from 'react'

export const curatedGuideArr = [
        {
          name: "Dairy",
          restriction: "allergy",
          title: "Dairy Friendly",
          bannerTextColor: "SecondaryColors.MutedBlue",
          bannerImage: "mascot-dairy.png",
          bannerBackColor: "SecondaryColors.Brown",
          freeOf: "free of milk, cheese, butter, cream, yogurt, sour cream, whey, casein, and lactose",
          designation: "dairy-free",
          type: "dairy allergy or intolerance",
          understandingTitle: "Understanding a Dairy Allergy",
          understandingRestriction: "A dairy allergy is a heightened sensitivity to dairy, the most common allergy-causing product for infants and young children. Approximately 70% of children with a dairy allergy tolerate baked cow milk, which refers to milk that has undergone extensive heating. Those who consume baked milk without adverse reactions may be more likely to outgrow their dairy allergy earlier than those who react to baked milk.",
          restrictionImage: "dairy.png",
          understandingTitle2: "Understanding a Lactose Intolerance",
          understandingIntolerance: "Food intolerances, unlike allergies, do not involve the immune system. Lactose intolerant individuals lack the enzyme lactase needed to break down lactose, a sugar found in milk and dairy products. While uncomfortable, lactose intolerance isn't life-threatening. Common symptoms include nausea, cramps, gas, bloating, and diarrhea after consuming dairy.",
          intoleranceImage: "lactose.png",
          cautionLabel: "Here are some of the most common ingredients that you should look out for:",
          ingredientList: "Butter, Cheese, Cream, Milk, Pudding, Sour cream, Yogurt",
          ingredientStarred: "",
          foodListTitle: "",
          foodLabel: "Here are some of the highest-risk foods for people with a dairy allergy or intolerance:",
          foodTitle1: "Creamy Soups and Sauces",
          foodBody1: "Cream-based soups like clam chowder, creamy pasta sauces, and sauces like béchamel or hollandaise often contain dairy.",
          foodImage1: "soup.png",
          foodTitle2: "Salads and Salad Dressings",
          foodBody2: "Some salads may include cheese, and creamy dressings like ranch or blue cheese may contain dairy ingredients.",
          foodImage2: "salad-dressing.png",
          foodTitle3: "Pizza and Pasta Dishes",
          foodBody3: "Pizza with cheese and pasta dishes with creamy sauces or cheese toppings can contain dairy.",
          foodImage3: "cheesy-pasta.png",
         foodTitle4: "Bread and Baked Goods",
          foodBody4: "Bread rolls, buns, and baked goods like croissants may contain butter or milk.",
          foodImage4: "cinnamon-rolls.png",
         link1: "https://www.foodallergy.org/living-food-allergies/food-allergy-essentials/common-allergens/milk",
          link2: "https://www.foodallergy.org/resources/milk-allergy-vs-lactose-intolerance",
         link3: "https://www.foodallergy.org/resources/recognizing-and-responding-reaction",
          allergyContent: "",
         allergyContentTitle: "",
          dietContent: "",
          dietContentTitle: ""
        },
        {
          name: "Egg",
          restriction: "allergy",
          title: "Egg Friendly",
          bannerTextColor: "SecondaryColors.Brown",
          bannerImage: "mascot-egg.png",
          bannerBackColor: "SecondaryColors.Pink",
         freeOf: "free of eggs",
         designation: "egg-free",
         type: "egg allergy",
          understandingTitle: "Understanding an Egg Allergy",
          understandingRestriction: "An egg allergy is a heightened sensitivity to eggs, one of the most common allergy-causing foods in infants and young children. Approximately 70% of children with an egg allergy tolerate baked egg. Additionally, most children outgrow their egg allergy, with 71% doing so by age 6.",
          restrictionImage: "eggs.png",
          understandingTitle2: "",
         understandingIntolerance: "",
         intoleranceImage: "",
          cautionLabel: "Here are some of the most common ingredients that you should look out for:",
          ingredientList: "Eggnog, Mayonnaise, Meringue",
          ingredientStarred: "",
          foodListTitle: "",
          foodLabel: "Here are some of the highest-risk foods for people with an egg allergy:",
         foodTitle1: "Baked Goods",
          foodBody1: "Cakes, cookies, pastries, muffins, and bread may contain eggs as a binding or leavening agent.",
          foodImage1: "baked-goods.png",
          foodTitle2: "Breakfast Foods",
          foodBody2: "Common breakfast foods like pancakes or waffles commonly contain eggs and should be avoided.",
          foodImage2: "waffle.png",
          foodTitle3: "Breads",
          foodBody3: "Bread may be coated with an egg wash, an egg and milk or water-based mixture to give the bread a shiny appearance.",
          foodImage3: "bread-sliced.png",
         foodTitle4: "Pasta",
          foodBody4: "Cooked pastas usually have eggs, while dry pastas are usually egg-free but may have cross-contamination risks.",
          foodImage4: "spaghetti.png",
         link1: "https://www.foodallergy.org/living-food-allergies/food-allergy-essentials/common-allergens/egg",
          link2: "https://www.foodallergy.org/resources/recognizing-and-responding-reaction",
         link3: "",
          allergyContent: "",
         allergyContentTitle: "",
          dietContent: "",
          dietContentTitle: ""
        },
        {
          name: "Fish",
          restriction: "allergy",
          title: "Fish Friendly",
          bannerTextColor: "SecondaryColors.Red",
          bannerImage: "mascot-fish.png",
          bannerBackColor: "SecondaryColors.MutedBlue",
         freeOf: "free of fish including anchovies, bass, catfish, cod, flounder, grouper, haddock, halibut, mahi-mahi, pike, salmon, snapper, swordfish, tilapia, trout, and tuna",
         designation: "fish-free",
         type: "fish allergy",
          understandingTitle: "Understanding a Fish Allergy",
          understandingRestriction: "A fish allergy involves heightened sensitivity to certain types of fish. Common triggers include salmon, tuna, catfish, and cod. If someone has an allergy to one type of fish, they might be allergic to others as well, so it's advisable to avoid all fish if they have a known allergy. Fish allergies often emerge in adulthood, with around 40% of individuals experiencing their first reaction during this period.",
          restrictionImage: "fish.png",
          understandingTitle2: "",
         understandingIntolerance: "",
         intoleranceImage: "",
          cautionLabel: "Here are some of the most common ingredients that you should look out for:",
          ingredientList: "Barbecue sauce, Caesar salad and Caesar dressing. Fish oil, Fish sticks, Worcestershire sauce",
          ingredientStarred: "",
          foodListTitle: "",
          foodLabel: "Here are some of the highest-risk foods for people with a fish allergy:",
         foodTitle1: "Sushi and Sashimi",
          foodBody1: "Traditional sushi and sashimi often contain raw or cooked fish, including salmon, tuna, eel, and mackerel.",
          foodImage1: "sushi.png",
          foodTitle2: "Salads",
          foodBody2: "Many salads and salad dressings (notably Caesar) feature anchovies, a common fish allergen.",
          foodImage2: "caesar.png",
          foodTitle3: "Multicultural Cuisines (especially African, Chinese, Indonesian, Thai, and Vietnamese)",
          foodBody3: "Dishes from multicultural cuisines may contain hidden sources of fish such as fish sauce in dishes like kimchi. Cross-contact with fish allergens is common even in fish-free options.",
          foodImage3: "kimchi.png",
         foodTitle4: "Sauces",
          foodBody4: "Sauces like Worcestershire sauce or fish sauce (used in many Asian cuisines) may contain fish or fish-derived ingredients.",
          foodImage4: "sauces.png",
         link1: "https://www.foodallergy.org/living-food-allergies/food-allergy-essentials/common-allergens/fish",
          link2: "https://www.foodallergy.org/resources/recognizing-and-responding-reaction",
         link3: "",
          allergyContent: "",
         allergyContentTitle: "",
          dietContent: "",
          dietContentTitle: ""
        },
        {
          name: "Gluten",
          restriction: "allergy",
          title: "Gluten Friendly",
          bannerTextColor: "SecondaryColors.BrightYellow",
          bannerImage: "mascot-gluten.png",
          bannerBackColor: "SecondaryColors.Green",
         freeOf: "free of wheat flour, barley, and rye",
         designation: "gluten-free",
         type: "gluten allergy or ee",
          understandingTitle: "Understanding Wheat Allergies and Celiac Disease",
          understandingRestriction: "A wheat allergy is a heightened sensitivity to wheat, which is most often reported in young children and may affect up to 1% of children in the U.S. Approximately two-thirds of children with a wheat allergy outgrow it by age 12. However, some individuals remain allergic to wheat throughout their lives. Wheat allergy and celiac disease differ; wheat allergy stems from an immune response to wheat proteins, causing allergy symptoms, while celiac disease is an autoimmune condition triggered by gluten, leading to intestinal inflammation.",
          restrictionImage: "wheat.png",
          understandingTitle2: "",
         understandingIntolerance: "",
         intoleranceImage: "",
          cautionLabel: "Here are some of the most common ingredients that you should look out for:",
          ingredientList: "Breadcrumbs, Couscous, Flour, Glucose syrup, Pasta, Semolina, Soy sauce, Wheat, Wheat grass",
          ingredientStarred: "",
          foodListTitle: "",
          foodLabel: "Here are some of the highest-risk foods for people with a gluten allergy or ee:",
         foodTitle1: "Pasta Dishes",
          foodBody1: "Many pasta dishes, such as spaghetti and macaroni, contain wheat-based pasta.",
          foodImage1: "spaghetti.png",
          foodTitle2: "Bread and Baked Goods",
          foodBody2: "Bread rolls, buns, croissants, and other baked goods served in restaurants may contain wheat flour.",
          foodImage2: "breads.png",
          foodTitle3: "Batter-Fried or Breaded Foods",
          foodBody3: "Foods that are batter-fried or breaded, such as fried chicken or fish, often contain wheat flour in the coating.",
          foodImage3: "fried-chicken.png",
         foodTitle4: "Beer and Ale",
          foodBody4: "Many restaurants serve beer and ale, which are brewed using barley, a gluten-containing grain, making them unsafe for individuals with a gluten ee.",
          foodImage4: "beer.png",
         link1: "https://www.foodallergy.org/living-food-allergies/food-allergy-essentials/common-allergens/wheat",
          link2: "https://www.foodallergy.org/resources/recognizing-and-responding-reaction",
         link3: "",
          allergyContent: "",
         allergyContentTitle: "",
          dietContent: "",
          dietContentTitle: ""
        },
        {
          name: "Halal",
          restriction: "diet",
          title: "Halal Diets",
          bannerTextColor: "SecondaryColors.Green",
          bannerImage: "mascot-halal.png",
          bannerBackColor: "SecondaryColors.BrightYellow",
         freeOf: "free of pork and alcohol, adhering to Halal dietary guidelines",
         designation: "halal-friendly",
         type: "halal dietary preference",
          understandingTitle: "Understanding a Halal Diet",
          understandingRestriction: "A Halal diet adheres to Islamic dietary laws and regulations, primarily consisting of foods that are permissible (Halal) according to Islamic principles. This diet excludes prohibited (Haram) foods such as pork and its by-products, alcohol, and any meat that is not slaughtered according to Islamic rituals. Halal cuisine must exclude ingredients sourced from forbidden (haram) origins. Additionally, it's essential to utilize utensils and equipment that have not been exposed to prohibited substances.",
          restrictionImage: "halal.png",
          understandingTitle2: "",
         understandingIntolerance: "",
         intoleranceImage: "",
          cautionLabel: "Here are some of the most common non-Halal food items that you should look out for:",
          ingredientList: "Pork and pork by-products, Alcohol and intoxicants, Meat from animals not slaughtered according to Islamic guidelines, Any food containing Haram ingredients or additives",
          ingredientStarred: "",
          foodListTitle: "Halal Delights: Menu Highlights",
          foodLabel: "",
         foodTitle1: "Grilled Chicken or Beef",
          foodBody1: "Tender and flavorful grilled chicken or beef dishes prepared according to Halal standards offer a satisfying and protein-rich option for Halal diet followers.",
          foodImage1: "grilled-chicken.png",
          foodTitle2: "Vegetable Pilaf or Biryani",
          foodBody2: "Aromatic rice dishes infused with spices, vegetables, and Halal-certified meats, offering a hearty and flavorful meal option suitable for Halal dietary preferences.",
          foodImage2: "pilaf.png",
          foodTitle3: "Hummus and Pita Bread",
          foodBody3: "Smooth and creamy hummus paired with soft pita bread, providing a delicious and nutritious appetizer or snack option that is compliant with Halal dietary guidelines.",
          foodImage3: "hummus.png",
         foodTitle4: "Falafel Wraps",
          foodBody4: "Crispy and savory falafel wrapped in warm pita bread with fresh vegetables and tahini sauce, delivering a delightful and Halal-friendly meal choice perfect for lunch or dinner.",
          foodImage4: "falafel-wrap.png",
         link1: "https://www.webmd.com/food-recipes/what-is-halal",
          link2: "https://www.mentalforlentils.com/dining-out-plant-based/",
         link3: "",
          allergyContent: "",
         allergyContentTitle: "",
          dietContent: "",
          dietContentTitle: ""
        },
        {
          name: "Keto",
          restriction: "diet",
          title: "Keto Diets",
          bannerTextColor: "SecondaryColors.Green",
          bannerImage: "mascot-keto.png",
          bannerBackColor: "SecondaryColors.BrightYellow",
         freeOf: "low in carbohydrates and high in healthy fats",
         designation: "keto-friendly",
         type: "keto dietary preference",
          understandingTitle: "Understanding a Keto Diet",
          understandingRestriction: "Keto diets emphasize low carbohydrate intake, focusing on foods high in healthy fats and moderate in protein. It aims to induce a metabolic state called ketosis, where the body burns fat for fuel instead of carbohydrates. This dietary approach can aid weight loss, improve blood sugar control, and enhance overall health.",
          restrictionImage: "keto.png",
          understandingTitle2: "",
         understandingIntolerance: "",
         intoleranceImage: "",
          cautionLabel: "Here are some of the most common high-carb food items that you should look out for:",
          ingredientList: "Bread and baked goods, Sugary snacks and desserts, Starchy vegetables (potatoes, corn, peas), Grains (rice, wheat, oats), Sugary beverages and fruit juices",
          ingredientStarred: "",
          foodListTitle: "Keto Delights: Menu Highlights",
          foodLabel: "",
         foodTitle1: "Grilled Meats and Seafood",
          foodBody1: "Lean cuts of beef, poultry, and fish cooked without breading or sugary marinades offer a satisfying and protein-rich option for keto dieters.",
          foodImage1: "meat-seafood.png",
          foodTitle2: "Leafy Green Salads",
          foodBody2: "Fresh salads with leafy greens, avocado, nuts, seeds, and olive oil-based dressings provide a nutrient-dense and low-carb meal choice suitable for keto followers.",
          foodImage2: "leafy-salad.png",
          foodTitle3: "Cauliflower Rice and Zoodles",
          foodBody3: "Substituting traditional rice or pasta with cauliflower rice or zucchini noodles (zoodles) offers a low-carb alternative that pairs well with various sauces and toppings.",
          foodImage3: "zoodles.png",
         foodTitle4: "Cheese Platters and Charcuterie",
          foodBody4: "Assorted cheeses, cured meats, olives, and nuts arranged on a platter offer a flavorful and keto-friendly option for sharing or as a light meal.",
          foodImage4: "charcuterie.png",
         link1: "https://www.webmd.com/diet/keto-diet-for-beginners",
          link2: "https://www.mentalforlentils.com/dining-out-plant-based/",
         link3: "",
          allergyContent: "",
         allergyContentTitle: "",
          dietContent: "",
          dietContentTitle: ""
        },
        {
          name: "Peanut",
          restriction: "allergy",
          title: "Peanut Friendly",
          bannerTextColor: "SecondaryColors.BrightYellow",
          bannerImage: "mascot-peanut.png",
          bannerBackColor: "SecondaryColors.Brown",
         freeOf: "free of peanuts",
         designation: "peanut-free",
         type: "peanut allergy",
          understandingTitle: "Understanding a Peanut Allergy",
          understandingRestriction: "A peanut allergy is a heightened sensitivity to peanuts, one of the most common allergy-causing foods. Peanuts, though not true nuts, are legumes with proteins similar to those in tree nuts. Individuals allergic to peanuts might also be allergic to tree nuts. Unlike some allergies that can be outgrown, peanut and tree nut allergies often persist throughout life.",
          restrictionImage: "peanuts.png",
          understandingTitle2: "",
         understandingIntolerance: "",
         intoleranceImage: "",
          cautionLabel: "Here are some of the most common ingredients that you should look out for:",
          ingredientList: "Peanut oil*, Peanut butter, Beer nuts, Ground nuts, Mixed nuts",
          ingredientStarred: "*Highly refined peanut oil is not required to be labeled as an allergen. Research indicates that most individuals with peanut allergies can consume this safely. If you have a peanut allergy, talk to your doctor to determine whether avoiding highly refined peanut oil is necessary.",
          foodListTitle: "",
          foodLabel: "Here are some of the highest-risk foods for people with a peanut allergy:",
         foodTitle1: "Cookies and Baked Goods",
          foodBody1: "Even if these items don't explicitly contain nuts, there's a chance of cross-contamination, especially in bakeries.",
          foodImage1: "cookies.png",
          foodTitle2: "Ice Cream",
          foodBody2: "Cross-contamination is common in ice cream parlors due to shared scoops. This risk extends to soft-serve ice cream, custard, water ice, and yogurt shops that use the same dispensing equipment for various flavors.",
          foodImage2: "ice-cream.png",
          foodTitle3: "African, Asian (especially Chinese, Indian, Indonesian, Thai, and Vietnamese), and Mexican Food",
          foodBody3: "Dishes from various global cuisines pose a significant risk of cross-contact with peanuts, even when ordering dishes without peanuts.",
          foodImage3: "asian-food.png",
         foodTitle4: "Sauces",
          foodBody4: "Look out for peanuts as a hidden ingredient. Some sauces, like chili, may use peanuts or peanut butter as a thickening agent.",
          foodImage4: "sauces.png",
         link1: "https://www.foodallergy.org/living-food-allergies/food-allergy-essentials/common-allergens/peanut",
          link2: "https://www.foodallergy.org/resources/recognizing-and-responding-reaction",
         link3: "",
          allergyContent: "",
         allergyContentTitle: "",
          dietContent: "",
          dietContentTitle: ""
        },
        {
          name: "Sesame",
          restriction: "allergy",
          title: "Sesame Friendly",
          bannerTextColor: "SecondaryColors.BrightYellow",
          bannerImage: "mascot-sesame.png",
          bannerBackColor: "SecondaryColors.Green",
         freeOf: "free of sesame",
         designation: "sesame-free",
         type: "sesame allergy",
          understandingTitle: "Understanding a Sesame Allergy",
          understandingRestriction: "A sesame allergy is a heightened sensitivity to sesame, which has increased globally over the past two decades. Sesame seeds, derived from the sesame plant, are widely used in global cuisines, ranging from baked goods to sushi. As of January 1, 2023, sesame emerged as the ninth major allergen.",
          restrictionImage: "sesame.png",
          understandingTitle2: "",
         understandingIntolerance: "",
         intoleranceImage: "",
          cautionLabel: "Here are some of the most common ingredients that you should look out for:",
          ingredientList: "Benne, Breadcrumbs, Sesame flour, Sesame oil, Sesame paste, Sesame salt (gomasio), Sesame seeds, Tahini",
          ingredientStarred: "",
          foodListTitle: "",
          foodLabel: "Here are some of the highest-risk foods for people with a sesame allergy:",
         foodTitle1: "Baked Goods",
          foodBody1: "Items such as bagels, bread, breadsticks, hamburger buns, and rolls often contain sesame seeds or sesame oil.",
          foodImage1: "breads.png",
          foodTitle2: "Asian Cuisine",
          foodBody2: "Be cautious of dishes cooked with sesame oil, commonly found in Asian cooking.",
          foodImage2: "asian-food.png",
          foodTitle3: "Dipping Sauces",
          foodBody3: "Baba ghanoush, hummus, and tahini sauce are commonly used as dips and dressings in Middle Eastern cuisine.",
          foodImage3: "sauces.png",
         foodTitle4: "Appetizer Dippers",
          foodBody4: "Sesame seeds may be found in bagel chips, pita chips, tortilla chips, crackers, and melba toast.",
          foodImage4: "dippers.png",
         link1: "https://www.foodallergy.org/living-food-allergies/food-allergy-essentials/common-allergens/sesame",
          link2: "https://www.foodallergy.org/resources/recognizing-and-responding-reaction",
         link3: "",
          allergyContent: "",
         allergyContentTitle: "",
          dietContent: "",
          dietContentTitle: ""
        },
        {
          name: "Shellfish",
          restriction: "allergy",
          title: "Shellfish Friendly",
          bannerTextColor: "SecondaryColors.Brown",
          bannerImage: "mascot-shellfish.png",
          bannerBackColor: "SecondaryColors.Pink",
         freeOf: "free of crustaceans (including shrimp, prawns, crab, and lobster) and mollusks (including clams, mussels, oysters, scallops, octopus, squid, abalone, and snail)",
         designation: "shellfish-free",
         type: "shellfish allergy",
          understandingTitle: "Understanding a Shellfish Allergy",
          understandingRestriction: "A shellfish allergy is a heightened sensitivity to shellfish, the most common allergy-causing food for adults. Shellfish can be divided into two groups: crustaceans and mollusks. Crustacean allergies are more common than mollusk allergies, with shrimp being the top allergen for both children and adults. Unlike some allergies that can be outgrown, shellfish allergies often persist throughout life.",
          restrictionImage: "shellfish.png",
          understandingTitle2: "",
         understandingIntolerance: "",
         intoleranceImage: "",
          cautionLabel: "Here are some of the most common ingredients that you should look out for:",
          ingredientList: "Crustaceans:\nCrab, Krill, Lobster, Prawns, Shrimp\n\nMollusks:\nClams, Mussels, Octopus, Oysters, Snails (escargot), Squid (calamari)",
          ingredientStarred: "",
          foodListTitle: "",
          foodLabel: "Here are some of the highest-risk foods for people with a shellfish allergy:",
         foodTitle1: "Pasta Dishes",
          foodBody1: "Common pasta dishes containing shellfish, such as lobster ravioli, shrimp scampi, and clam linguine, should be avoided.",
          foodImage1: "scampi.png",
          foodTitle2: "Seafood Appetizers",
          foodBody2: "Common appetizers containing shellfish, such as shrimp cocktail and crab cakes, should be avoided.",
          foodImage2: "crab-cakes.png",
          foodTitle3: "Soup and Chowder",
          foodBody3: "Soups and chowders containing shellfish, such as lobster bisque and clam chowder soup, should be avoided.",
          foodImage3: "chowder.png",
         foodTitle4: "",
          foodBody4: "",
          foodImage4: "",
         link1: "https://www.foodallergy.org/living-food-allergies/food-allergy-essentials/common-allergens/shellfish",
          link2: "https://www.foodallergy.org/resources/recognizing-and-responding-reaction",
         link3: "",
          allergyContent: "",
         allergyContentTitle: "",
          dietContent: "",
          dietContentTitle: ""
        },
        {
          name: "Soy",
          restriction: "allergy",
          title: "Soy Friendly",
          bannerTextColor: "SecondaryColors.Green",
          bannerImage: "mascot-soy.png",
          bannerBackColor: "SecondaryColors.MutedBlue",
         freeOf: "free of soybeans and soy-derived ingredients",
         designation: "soy-free",
         type: "soy allergy",
          understandingTitle: "Understanding a Soy Allergy",
          understandingRestriction: "A soy allergy is a heightened sensitivity to soybeans and soy-derived ingredients. Soybeans, like peanuts, are members of the legume family. Studies have shown that up to 88% of individuals with soy allergies also have a peanut allergy or sensitivity. Most children eventually outgrow their soy allergy.",
          restrictionImage: "soybeans.png",
          understandingTitle2: "",
         understandingIntolerance: "",
         intoleranceImage: "",
          cautionLabel: "Here are some of the most common ingredients that you should look out for:",
          ingredientList: "Edamame, Miso \nSoy oil*, Soy sauce, Tempeh, Tofu",
          ingredientStarred: "*Highly refined soy oil is not required to be labeled as an allergen. Research indicates that most individuals with soy allergies can consume this safely, as well as soy lecithin. If you have a soy allergy, talk to your doctor to determine whether avoiding highly refined soy oil or soy lecithin is necessary.",
          foodListTitle: "",
          foodLabel: "Here are some of the highest-risk foods for people with a soy allergy:",
         foodTitle1: "Asian Cuisine",
          foodBody1: "Dishes such as stir-fries, tofu-based dishes, and miso soup often contain soy ingredients. Even seemingly soy-free dishes may have been cooked with soy-based sauces or oils, increasing the risk of cross-contact.",
          foodImage1: "asian-food.png",
          foodTitle2: "Grains Prepared with Soy",
          foodBody2: "Look out for soy as a hidden ingredient since it may be present in bread, pasta, tortillas, and rice dishes.",
          foodImage2: "baguette.png",
          foodTitle3: "Soups and Stews",
          foodBody3: "Soups and stews made with vegetable broth may contain soy-based ingredients for flavor enhancement.",
          foodImage3: "stew.png",
         foodTitle4: "Sauces and Gravies",
          foodBody4: "Sauces and gravies may use vegetable starches derived from soy as a thickening agent.",
          foodImage4: "sauces.png",
         link1: "https://www.foodallergy.org/living-food-allergies/food-allergy-essentials/common-allergens/soy",
          link2: "https://www.foodallergy.org/resources/recognizing-and-responding-reaction",
         link3: "",
          allergyContent: "",
         allergyContentTitle: "",
          dietContent: "",
          dietContentTitle: ""
        },
        {
          name: "Treenut",
          restriction: "allergy",
          title: "Tree Nut Friendly",
          bannerTextColor: "SecondaryColors.Brown",
          bannerImage: "mascot-treenut.png",
          bannerBackColor: "SecondaryColors.MutedBlue",
         freeOf: "free of almonds, Brazil nuts, cashews, chestnuts, hazelnuts, macadamia nuts, pecans, pine nuts, pistachios, and walnuts",
         designation: "tree nut-free",
         type: "tree nut allergy",
          understandingTitle: "Understanding a Tree Nut Allergy",
          understandingRestriction: "A tree nut allergy is a heightened sensitivity to one or more tree nuts, one of the most common allergy-causing foods. Although only about 40% of children with tree nut allergies have a peanut allergy, there's a significant chance of cross-reactivity among different tree nuts, with around 50% of children allergic to one tree nut also being allergic to another. Unlike some allergies that can be outgrown, tree nut allergies often persist throughout life.",
          restrictionImage: "nuts.png",
          understandingTitle2: "",
         understandingIntolerance: "",
         intoleranceImage: "",
          cautionLabel: "Here are some of the most common ingredients that you should look out for:",
          ingredientList: "Pesto, Nut milk (e.g., almond milk, cashew milk), Nut oils (e.g., walnut oil, almond oil), Nut paste (e.g., almond paste)",
          ingredientStarred: "",
          foodListTitle: "",
          foodLabel: "Here are some of the highest-risk foods for people with a tree nut allergy:",
         foodTitle1: "Desserts and Baked Goods",
          foodBody1: "Always inquire about desserts and baked goods, as they may contain almond flour, ground nuts, or nut extracts.",
          foodImage1: "baked-goods.png",
          foodTitle2: "Ice Cream",
          foodBody2: "Flavors like pistachio may contain actual tree nuts or traces of them. Cross-contamination is also common in ice cream parlors due to shared scoops. This risk extends to soft-serve ice cream, custard, water ice, and yogurt shops that use the same dispensing equipment for various flavors.",
          foodImage2: "ice-cream.png",
          foodTitle3: "African and Asian Food (especially Chinese, Indian, Thai, and Vietnamese)",
          foodBody3: "Dishes from various global cuisines pose a significant risk of cross-contact with tree nuts, even when ordering dishes without tree nuts.",
          foodImage3: "asian-food.png",
         foodTitle4: "Salads",
          foodBody4: "Candied nuts, such as almonds, or pecans, are common salad toppings.",
          foodImage4: "salad.png",
         link1: "https://www.foodallergy.org/living-food-allergies/food-allergy-essentials/common-allergens/tree-nut",
          link2: "https://www.foodallergy.org/resources/recognizing-and-responding-reaction",
         link3: "",
          allergyContent: "",
         allergyContentTitle: "",
          dietContent: "",
          dietContentTitle: ""
        },
        {
          name: "Vegan",
          restriction: "diet",
          title: "Vegan Diets",
          bannerTextColor: "SecondaryColors.Green",
          bannerImage: "mascot-vegan.png",
          bannerBackColor: "SecondaryColors.BrightYellow",
         freeOf: "free of animal products, including meat, poultry, fish, dairy, eggs, and honey",
         designation: "vegan-friendly",
         type: "vegan dietary preference",
          understandingTitle: "Understanding a Vegan Diet",
          understandingRestriction: "Vegan diets mainly consist of plant-based foods like fruits, vegetables, grains, legumes, nuts, and seeds. Individuals who choose to follow a vegan diet commonly do so for reasons related to animal welfare, environmental impact, or their personal health. Like vegetarians, vegans do not eat food derived from animal flesh, including meat, poultry, and fish. However, vegan diets are more strict than vegetarian diets because they exclude all animal foods and products, including dairy, eggs, and honey.",
          restrictionImage: "vegan.png",
          understandingTitle2: "",
         understandingIntolerance: "",
         intoleranceImage: "",
          cautionLabel: "Here are some of the most common non-vegan food items that you should look out for:",
          ingredientList: "Meat (beef, pork, lamb, etc.), Poultry (chicken, turkey, duck, etc.), Fish and seafood (crabs, clams, mussels, etc.), Dairy products (milk, ice cream, cheese, yogurt, butter, etc.), Eggs, Honey and other bee products",
          ingredientStarred: "",
          foodListTitle: "Vegan Delights: Menu Highlights",
          foodLabel: "",
         foodTitle1: "Veggie Burgers",
          foodBody1: "Plant-based patties made from ingredients like beans, grains, and vegetables, providing a savory and satisfying alternative to traditional burgers.",
          foodImage1: "veggie-burger.png",
          foodTitle2: "Buddha Bowls",
          foodBody2: "Nourishing bowls typically made of vegetables, grains (such as quinoa or rice), legumes, and flavorful dressings, offering a balanced and colorful option.",
          foodImage2: "buddha-bowl.png",
          foodTitle3: "Avocado Toast",
          foodBody3: "Sliced avocado served atop toasted bread, often accompanied by seasonings, greens, or other toppings, delivering a creamy and nutrient-rich dish perfect for breakfast or brunch.",
          foodImage3: "avocado-toast.png",
         foodTitle4: "Vegetable Stir Fry",
          foodBody4: "A flavorful combination of assorted vegetables quickly cooked in a savory sauce, served over rice or noodles, providing a vibrant and customizable meal packed with nutrients.",
          foodImage4: "stirfry.png",
         link1: "https://www.webmd.com/diet/vegan-diet-overview",
          link2: "https://www.mentalforlentils.com/dining-out-plant-based/",
         link3: "",
          allergyContent: "",
         allergyContentTitle: "",
          dietContent: "",
          dietContentTitle: ""
        },
        {
          name: "Vegetarian",
          restriction: "diet",
          title: "Vegetarian Diets",
          bannerTextColor: "SecondaryColors.Green",
          bannerImage: "mascot-vegetarian.png",
          bannerBackColor: "SecondaryColors.Pink",
         freeOf: "free of meat, fish, and fowl flesh",
         designation: "vegetarian-friendly",
         type: "vegetarian dietary preference",
          understandingTitle: "Understanding a Vegetarian Diet",
          understandingRestriction: "Vegetarian diets mainly consist of plant-based foods like fruits, vegetables, grains, legumes, nuts, and seeds. Individuals who choose to follow a vegetarian diet commonly do so for reasons related to animal welfare or their personal health. Unlike vegans, vegetarians may include dairy and eggs in their diet while abstaining from animal flesh, including meat, poultry, and fish.",
          restrictionImage: "vegetarian.png",
          understandingTitle2: "",
         understandingIntolerance: "",
         intoleranceImage: "",
          cautionLabel: "Here are some of the most common non-vegetarian food items that you should look out for:",
          ingredientList: "Meat (beef, pork, lamb, etc.), Poultry (chicken, turkey, duck, etc.), Fish and seafood (crabs, clams, mussels, etc.)",
          ingredientStarred: "",
          foodListTitle: "Vegetarian Delights: Menu Highlights",
          foodLabel: "",
         foodTitle1: "Veggie Burgers",
          foodBody1: "Plant-based patties made from ingredients like beans, grains, and vegetables, providing a savory and satisfying alternative to traditional burgers.",
          foodImage1: "veggie-burger.png",
          foodTitle2: "Buddha Bowls",
          foodBody2: "Nourishing bowls typically made of vegetables, grains (such as quinoa or rice), legumes, and flavorful dressings, offering a balanced and colorful option.",
          foodImage2: "buddha-bowl.png",
          foodTitle3: "Avocado Toast",
          foodBody3: "Sliced avocado served atop toasted bread, often accompanied by seasonings, greens, or other toppings, delivering a creamy and nutrient-rich dish perfect for breakfast or brunch.",
          foodImage3: "avocado-toast.png",
         foodTitle4: "Vegetable Stir Fry",
          foodBody4: "A flavorful combination of assorted vegetables quickly cooked in a savory sauce, served over rice or noodles, providing a vibrant and customizable meal packed with nutrients.",
          foodImage4: "stirfry.png",
         link1: "https://www.webmd.com/diet/vegan-diet-overview",
          link2: "https://www.mentalforlentils.com/dining-out-plant-based/",
         link3: "",
          allergyContent: "",
         allergyContentTitle: "",
          dietContent: "",
          dietContentTitle: ""
        },
];